// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLeKyh3TllB6i1s0YIVwL-11oWdE46PhA',
    appId: '1:508155627538:web:9e56b48460b68201a270cb',
    messagingSenderId: '508155627538',
    projectId: 'bookish-fishbowl',
    authDomain: 'bookish-fishbowl.firebaseapp.com',
    storageBucket: 'bookish-fishbowl.appspot.com',
    measurementId: 'G-Y45P9GLMGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3OBzqtBOgSukEB5mdpUwauXUpa62eMPk',
    appId: '1:508155627538:android:a3b1fc9835dcf886a270cb',
    messagingSenderId: '508155627538',
    projectId: 'bookish-fishbowl',
    storageBucket: 'bookish-fishbowl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC3PoGEQOa-WGxO83p9NFr0yoc98XSd7s',
    appId: '1:508155627538:ios:7d79bba0fb06d23ba270cb',
    messagingSenderId: '508155627538',
    projectId: 'bookish-fishbowl',
    storageBucket: 'bookish-fishbowl.appspot.com',
    iosBundleId: 'com.example.bookishFishfillet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC3PoGEQOa-WGxO83p9NFr0yoc98XSd7s',
    appId: '1:508155627538:ios:2527eb796e90d81aa270cb',
    messagingSenderId: '508155627538',
    projectId: 'bookish-fishbowl',
    storageBucket: 'bookish-fishbowl.appspot.com',
    iosBundleId: 'com.example.bookishFishfillet.RunnerTests',
  );
}
